name: SonarQube Runner

on:
  workflow_dispatch:

jobs:
  run-sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Set Variables
        id: set-variables
        run: |
          # Set the variables
          echo "::set-output name=SONARQUBE_URL::http://4.194.13.61:9000"
          echo "::set-output name=SONARQUBE_TOKEN::${{ secrets.SONARQUBE_TOKEN }}"
          echo "::set-output name=PROJECT_KEY::from-template-project"
          echo "::set-output name=PROJECT_NAME::from-template-project"
          echo "::set-output name=DESTINATION_DIR::/home/runner/work/hello-nodejs/hello-nodejs"
          echo "::set-output name=REPOSITORY_URL::https://github.com/MuZikZz-Org/hello-nodejs"

      - name: Run SonarQube Scanner
        uses: MuZikZz-Org/.github/workflow-templates/sonarqube@main
        with:
          SONARQUBE_URL: ${{ steps.set-variables.outputs.SONARQUBE_URL }} # Pass other_variable as an input
          SONARQUBE_TOKEN: ${{ steps.set-variables.outputs.SONARQUBE_TOKEN }}
          PROJECT_KEY: ${{ steps.set-variables.outputs.PROJECT_KEY }}
          PROJECT_NAME: ${{ steps.set-variables.outputs.PROJECT_NAME }}
          DESTINATION_DIR: ${{ steps.set-variables.outputs.DESTINATION_DIR }}
          REPOSITORY_URL: ${{ steps.set-variables.outputs.REPOSITORY_URL }}
        # with:
        #   repository: "test-sonar-cross-repo"  
