name: 'Terraform Apply'

on:
  workflow_dispatch:
    inputs:
      environment_choice:
        type: choice
        required: true
        description: Select environment
        options:
          - dev
          - alpha
          - staging
          - preprod
          - prod
      resource_choice:
        type: choice
        description: Select resource
        options:
          - vm
          - something

jobs:
  terraform_apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure Terraform
        run: terraform init

      - name: Select Terraform directory
        id: select_dir
        run: |
          if [ -d "${INPUT_resource_choice}" ]; then
          echo "${INPUT_resource_choice}"
          # cd "${INPUT_resource_choice}"
        shell: bash

