name: 'Terraform Apply'

on:
  workflow_dispatch:
    inputs:
      environment_choice:
        type: choice
        required: true
        description: Select environment
        options:
          - dev
          - alpha
          - staging
          - preprod
          - prod
      resource_choice:
        type: choice
        required: true
        description: Select resource
        options:
          - vm
          - something

jobs:
  login:
    name: login
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_VERSION: 'latest'

    defaults:
      run:
        shell: bash

    steps:
      - name: Check out code  
        uses: actions/checkout@v1
    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}        

      - name: echo
        id: echo
        run: echo "Helloooooooo"
